### ISSUE TITLE
Build fails with upower-0.99.4 Error

### ISSUE THREAD

**Issue by markbirss** [flatmax/NanoPi.Neo4.buildroot.external#3]
I get a build failure with upower-0.99.4

```
>>> upower 0.99.4 Fixing libtool files
upower: installs files in /home/user/build/neo/buildroot.neo4/output/host/aarch64-buildroot-linux-gnu/sysroot//home/user/build/neo/buildroot.neo4/output
package/pkg-generic.mk:270: recipe for target '/home/user/build/neo/buildroot.neo4/output/build/upower-0.99.4/.stamp_staging_installed' failed
make: *** [/home/user/build/neo/buildroot.neo4/output/build/upower-0.99.4/.stamp_staging_installed] Error 1
```

**Comment by flatmax** [comment]
This is a buildroot repo bug.
You need to checkout version e1a43490e9ab24a3a249ab1224e236db47c53145 of buildroot for this to work :
cd buildroot.neo4
git reset --hard HEAD
rm package/*.tgz
git checkout e1a43490e9ab24a3a249ab1224e236db47c53145

Now start again :
make distclean
. NanoPi.Neo4/setup.sh yourPath/buildroot.neo4
make
