### ISSUE TITLE
No HDMI output: ? Direct firmware load for rockchip/dptx.bin failed with error -2

### ISSUE THREAD

**Issue by markbirss** [flatmax/NanoPi.Neo4.buildroot.external#4]
I finally received my board but only see the FriendlyElec uboot logo then no more video output

Have attached serial console and see

[   10.660791] cdn-dp fec00000.dp: Direct firmware load for rockchip/dptx.bin failed with error -2

**Comment by flatmax** [comment]
I believe it eventually has success in loading the file, can you confirm ?

**Comment by markbirss** [comment]
I have added the file to /lib/firmware but still same error and no hdmi
output.

The kernel config might need more drivers enabled ?

Or it a issue with the current kernel version ?

**Comment by flatmax** [comment]
ok, so the dptx.bin is unrelated to HDMI output.

I will add it the dptx.bin to the repo overlay to fix that problem.

To run the HDMI display, do like so :

. ./westonSetup.sh

weston --tty 2


Matt

**Comment by flatmax** [comment]
You can now enable weston autostarting using the following config variables :
BR2_PACKAGE_NANOPI_SCRIPTS=y
BR2_PACKAGE_NANOPI_SCRIPTS_INIT_WESTON=y

**Comment by markbirss** [comment]
I have built the image again enabling those config variables in .config

BR2_PACKAGE_NANOPI_SCRIPTS=y
BR2_PACKAGE_NANOPI_SCRIPTS_INIT_WESTON=y

however still no HDMI terminal output is shown ?

This is last few lines of the serial console ouput

`Starting ntpd: OK
Starting sshd: OK
Starting weston
Starting input-event-daemon: done
Date: 2013-01-18 UTC
[09:04:47.793] weston 5.0.0
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
               Build: unknown (not built from git or tarball)
[09:04:47.809] Command line: weston --tty 2
[09:04:47.813] OS: Linux, 4.4.143, #1 SMP Sat Jan 26 15:22:37 SAST 2019, aarch64
[09:04:47.821] Starting with no config file.
[09:04:47.826] Output repaint window is 7 ms maximum.
[09:04:47.831] Loading module '/usr/lib/libweston-5/drm-backend.so'

Welcome to RK3399 Buildroot
rk3399 login: [09:04:47.982] Failed to load module: /usr/lib/libweston-5/drm-backend.so: undefined symbol: gbm_bo_get_offset
[09:04:47.986] fatal: failed to create compositor backend`

**Comment by markbirss** [comment]
the closest info related to weston i could find was from Linux From Scratch on the Pi
http://intestinate.com/pilfs/beyond.html#wayland

Don't know if that helps

**Comment by flatmax** [comment]
Did you make distclean before you rant setup ?

Like so :

1] In yourPath/buildroot.neo4 :  make distclean

2] Run the nanopi neo4 setup.sh script again : . NanoPi.Neo4/setup.sh 
yourPath/buildroot.neo4

3] make

Thing for you to lookout for is the libmali build directory :

yourPath/buildroot.neo4/output/build/libmali-721653b5b3b525a4f80d15aa7e2f9df7b7e60427

It should be present. Then in output/target/usr/lib/ you should see many 
libraries linking against libmali :

buildroot.neo4b$ ls -l output/target/usr/lib/ | grep mali
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libEGL.so -> libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libEGL.so.1 -> libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libgbm.so -> libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libgbm.so.1 -> libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libGLESv1_CM.so -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libGLESv1_CM.so.1 -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libGLESv2.so -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libGLESv2.so.2 -> 
libmali.so
-rw-r--r-- 1 flatmax flatmax 26269888 Jan 25 12:57 
libmali-midgard-t86x-r14p0-wayland.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libMaliOpenCL.so -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       37 Jan 25 12:06 libmali.so -> 
libmali-midgard-t86x-r14p0-wayland.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libMali.so -> libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libOpenCL.so -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libwayland-egl.so -> 
libmali.so
lrwxrwxrwx 1 flatmax flatmax       10 Jan 25 12:06 libwayland-egl.so.1 
-> libmali.so

**Comment by markbirss** [comment]
Will check again, and report back

**Comment by markbirss** [comment]
Yes I did

I can see the file/s in the output/target/usr/lib directory

[image: yes.png]

So my image has been build with them included, but when powering up the
Nano Pi NEO with HDMI screen attached I only see the friendly arm u-boot
logo then nothing ?

Is it suppose to show a console on the HDMI output ?

**Comment by markbirss** [comment]
I did

mkdir /run/user
export XDG_RUNTIME_DIR=/run/user/$UID
weston --tty 2

[image: 2.png]

**Comment by flatmax** [comment]
I did a test myself and this works :

1] make distclean in the buildroot.neo4 directory.

2] Edit configs/neo4_custom_defconfig and un-comment the following lines :

BR2_PACKAGE_NANOPI_SCRIPTS=y
BR2_PACKAGE_NANOPI_SCRIPTS_INIT_WESTON=y

2] cd; . ./NanaoPi.Neo4/setup.sh buildroot.neo4

3] In buildroot.neo4 : make

4] Burn the image to the sdcard  (replacing sdxx with your device) :

sudo buildroot.neo4b/output/images/sd-fuse-rk3399/fusing.sh /dev/sdxx 
buildroot


Plug in HDMI and it should work out of the box !

Matt

**Comment by markbirss** [comment]
Hi Matt

Thank you kindly for your effort and feedback/patience.

I went back and followed your instructions from fresh made the
neo4_custom_defconfig config changes and wrote the
"rk3399-buildroot-sd4g-20190201.img" using Etcher

I connected up and booted up into a Wayland Terminal

Thank you very much

Regards

https://github.com/flatmax/NanoPi.Neo4.buildroot.external

Initial setup

Clone buildroot. For example :

cd yourPath
git clone git://git.busybox.net/buildroot buildroot.neo4
cd buildroot.neo4
git checkout e1a43490e9ab24a3a249ab1224e236db47c53145

To make the system
Edit neo4_custom_defconfig and un-comment the following lines :

BR2_PACKAGE_NANOPI_SCRIPTS=y
BR2_PACKAGE_NANOPI_SCRIPTS_INIT_WESTON=y

. NanoPi.Neo4/setup.sh yourPath/buildroot.neo4

<https://github.com/flatmax/NanoPi.Neo4.buildroot.external#ensure-you-have-your-buildroot-net-downloads-directory-setup>ensure
you have your buildroot net downloads directory setup

mkdir yourPath/buildroot.dl

<https://github.com/flatmax/NanoPi.Neo4.buildroot.external#build-the-system>build
the system

make
